version: '3'
services:
  web1:
    build: .
    container_name: flask_web1
    restart: always
    ports:
      - "5001:5000"
    networks:
      - flask_network

  web2:
    build: .
    container_name: flask_web2
    restart: always
    ports:
      - "5002:5000"
    networks:
      - flask_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
